name: Build and Upload ZIP Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create a ZIP file
      - name: Create ZIP file
        run: |
          mkdir -p subfolder
          cd my_app
          zip -r ../subfolder/my_app.zip *

      # Upload the ZIP file as an artifact
      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: artifact-zip
          path: subfolder/my_app.zip

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
